FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    libeccodes0 \
    libeccodes-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY api ./api
COPY scripts ./scripts

EXPOSE 8001

CMD ["uvicorn", "api.app.main:app", "--host", "0.0.0.0", "--port", "8001"]
